### ISSUE TITLE
An undocumented assumption on encrypting yaml/json only

### ISSUE THREAD

**Issue by consideRatio** [yuvipanda/pre-commit-hook-ensure-sops#1]
`sops` is able to encrypt arbitrary files, but has special support for `yaml`, `json`, and `toml` if I recall correctly. This action seem to have an undocumented assumption that can be broken for files that are encrypted but not `yaml` or `json`.

I suggest this assumption is made explicit in the readme.

**Comment by yuvipanda** [comment]
@consideRatio if you encrypt *any* file with sops, binary or otherwise, it gets converted into JSON! So all sops encrypted files are actually JSON or YAML (I didn't know it supported TOML).

**Comment by yuvipanda** [comment]
See https://github.com/2i2c-org/infrastructure/blob/master/eksctl/ssh-keys/openscapes.key for example. It's an ssh-key, so a plaintext file. Just gets converted to JSON automatically.

**Comment by yuvipanda** [comment]
@consideRatio yep! Hence it's always safe to assume that a `sops` encrypted file is parseable as YAML, no matter what - as all JSON is parseable as YAML too. This is very helpful in many places when you want to call in `sops` only if necessary - just parse the file regardless, and just pass it to `sops` only if there's a `sops` key in it! I use this quite a bit in hubploy...
