### ISSUE TITLE
Add unit tests for the package

### ISSUE THREAD

**Issue by nialov** [yuvipanda/pre-commit-hook-ensure-sops#16]
# Problem

There is no way to verify that the package works without some kind of test framework that can be run after installation.

# Solution

I suggest starting with a few simple tests for the `validate_enc` and `check_file` functions. `pytest`seems reasonable as the test runner.

Let me know if you want me to make a pull request for this! I would add `pytest` to `setup.py` `test_requires` dependencies and draft a few simple tests that check a valid and invalid file at the very least.

**Comment by yuvipanda** [comment]
Yes, would *love* to have a PR with some tests! Thank you so much!
