### ISSUE TITLE
Code uses ruamel YAML parser which fails if JSON file contains hard tabs \t

### ISSUE THREAD

**Issue by sgibson91** [yuvipanda/pre-commit-hook-ensure-sops#9]
We established in 2i2c that JSON is valid YAML _unless_ a JSON file contains a hard tab character `\t` as opposed to pure whitespace. We corrected for this in our deployer code, but evidently not in this hook.

Error message from a [recent pre-commit run](https://results.pre-commit.ci/run/github/291960479/1672622271.qIC7hX0qRnaGuy-2wgSS4w):

```
ruamel.yaml.scanner.ScannerError: while scanning for the next token
found character '\t' that cannot start any token
  in "config/clusters/nasa-cryo/enc-deployer-credentials.secret.json", line 2, column 1
```

**Comment by yuvipanda** [comment]
Turns out this worked fine in python 3.10 for some reason but fails in 3.11. Fixed!

I had also earlier made a v1.0 tag but the package itself was tagged v0.1. I've 'fixed' this now, made a real 1.0 tag as well - so no changes needed in config.
